apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  JWT_SECRET: replace-with-strong-shared-jwt-secret

  # For MongoDB Atlas use mongodb+srv://...
  MONGO_URI: "mongodb+srv://admin:iu2Ug76JXIsQ2Og0@cluster0.cenmx6l.mongodb.net/mern_crud?retryWrites=true&w=majority"

  # Used only when deploying local MongoDB from 03-mongodb.yaml
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password

  SMTP_USER: replace-with-smtp-user
  SMTP_PASS: replace-with-smtp-password
  GEMINI_API_KEY: ""
