apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  JWT_SECRET: replace-with-strong-shared-jwt-secret

  MONGO_URI: replace-with-your-single-mongo-uri

  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password

  SMTP_USER: replace-with-smtp-user
  SMTP_PASS: replace-with-smtp-password
  GEMINI_API_KEY: replace-with-gemini-api-key
