apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  JWT_SECRET: replace-with-strong-shared-jwt-secret

  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password

  MONGO_URI_GATEWAY: mongodb://root:password@mongodb:27017/gateway-db?authSource=admin
  MONGO_URI_AUTH: mongodb://root:password@mongodb:27017/auth-db?authSource=admin
  MONGO_URI_PATIENT: mongodb://root:password@mongodb:27017/patient-db?authSource=admin
  MONGO_URI_DOCTOR: mongodb://root:password@mongodb:27017/doctor-db?authSource=admin
  MONGO_URI_APPOINTMENT: mongodb://root:password@mongodb:27017/appointment-db?authSource=admin
  MONGO_URI_NOTIFICATION: mongodb://root:password@mongodb:27017/notification-db?authSource=admin
  MONGO_URI_AI: mongodb://root:password@mongodb:27017/ai-db?authSource=admin

  SMTP_USER: replace-with-smtp-user
  SMTP_PASS: replace-with-smtp-password
  GEMINI_API_KEY: replace-with-gemini-api-key
