apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-config
  namespace: smart-healthcare
data:
  NODE_ENV: production

  AUTH_SERVICE_URL: http://auth-service:4001
  PATIENT_SERVICE_URL: http://patient-service:4002
  DOCTOR_SERVICE_URL: http://doctor-service:4003
  APPOINTMENT_SERVICE_URL: http://appointment-service:4004
  NOTIFICATION_SERVICE_URL: http://notification-service:4005
  AI_SERVICE_URL: http://ai-service:4006

  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  EMAIL_FROM: noreply@healthcare.com
